# Define site datum - best to be in the center of the field of interest
datum_latitude: &datum_latitude -0.5240515126879408
datum_longitude: &datum_longitude 53.26851890186007


# Define GNSS Fence coordinates [lat, lon]
gnss_fence:
  gnss_fence_coords: [[-0.5243216269711615, 53.26873036880698], [-0.5242994990874461, 53.26865710106747], [-0.5244146091376378, 53.26864562147315], [-0.5243301379798693, 53.26829254815776], [-0.5239610102988479, 53.26832917397978], [-0.5240684530796702, 53.26874404418737], [-0.5243216269711615, 53.26873036880698]]

# Define map size (x east, y north) in meters from the datum
gmapping:
  xmin: -100
  xmax: 100
  ymin: -100
  ymax: 100

mapviz_initialize_origin:
  local_xy_origins:
    - {
    name: dont_change_this,
    latitude: *datum_latitude,
    longitude: *datum_longitude,
    altitude: 100.0,
    heading: 0.0
    }

navsat_transform_node:
  magnetic_declination_radians: 0.0
  yaw_offset: 0.0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: true
  datum: [ *datum_latitude, *datum_longitude, 0.0]

