- tunnel_0:
  - row_0:
      coordinates:
      - x: 20.47
        y: -11.17
      - x: 20.89
        y: -14.15
      - x: 21.37
        y: -17.15
      - x: 21.82
        y: -20.12
      - x: 22.22
        y: -23.11
      - x: 22.65
        y: -26.08
      - x: 23.1
        y: -29.01
      - x: 23.53
        y: -32.05
      - x: 24.12
        y: -35.26
      orientation: 4.86
  - row_1:
      coordinates:
      - x: 19.19
        y: -11.68
      - x: 19.65
        y: -14.65
      - x: 20.08
        y: -17.6
      - x: 20.5
        y: -20.55
      - x: 20.95
        y: -23.55
      - x: 21.37
        y: -26.55
      - x: 21.8
        y: -29.5
      - x: 22.2
        y: -32.25
      - x: 22.55
        y: -34.9
      orientation: 4.86
  - row_2:
      coordinates:
      - x: 17.9
        y: -11.85
      - x: 18.34
        y: -14.85
      - x: 18.8
        y: -17.8
      - x: 19.2
        y: -20.8
      - x: 19.65
        y: -23.79
      - x: 20.1
        y: -26.7
      - x: 20.5
        y: -29.7
      - x: 20.9
        y: -32.4
      - x: 21.3
        y: -35.1
      orientation: 4.86
  - row_3:
      coordinates:
      - x: 16.54
        y: -12.05
      - x: 17.0
        y: -15.0
      - x: 17.45
        y: -17.95
      - x: 17.87
        y: -20.96
      - x: 18.35
        y: -23.95
      - x: 18.75
        y: -26.92
      - x: 19.2
        y: -29.9
      - x: 19.6
        y: -32.6
      - x: 20.05
        y: -35.3
      orientation: 4.86
  - row_4:
      coordinates:
      - x: 15.22
        y: -12.25
      - x: 15.67
        y: -15.19
      - x: 16.11
        y: -18.19
      - x: 16.55
        y: -21.15
      - x: 17.0
        y: -24.15
      - x: 17.45
        y: -27.1
      - x: 17.87
        y: -30.1
      - x: 18.25
        y: -32.85
      - x: 18.65
        y: -35.5
      orientation: 4.86
  - row_5:
      coordinates:
      - x: 13.9
        y: -12.45
      - x: 14.34
        y: -15.35
      - x: 14.8
        y: -18.35
      - x: 15.25
        y: -21.4
      - x: 15.7
        y: -24.35
      - x: 16.1
        y: -27.3
      - x: 16.54
        y: -30.31
      - x: 16.95
        y: -33.04
      - x: 17.35
        y: -35.7
      orientation: 4.86
  - row_6:
      coordinates:
      - x: 12.55
        y: -12.26
      - x: 12.99
        y: -15.21
      - x: 13.45
        y: -18.24
      - x: 13.9
        y: -21.3
      - x: 14.34
        y: -24.27
      - x: 14.75
        y: -27.2
      - x: 15.2
        y: -30.2
      - x: 15.63
        y: -33.2
      - x: 16.08
        y: -36.21
      orientation: 4.86
- tunnel_1:
  - row_0:
      coordinates:
      - x: 28.42
        y: -10.01
      - x: 28.85
        y: -13.05
      - x: 29.27
        y: -16.04
      - x: 29.69
        y: -18.99
      - x: 30.15
        y: -21.97
      - x: 30.6
        y: -24.95
      - x: 31.04
        y: -27.95
      - x: 31.5
        y: -30.9
      - x: 31.95
        y: -33.89
      orientation: 4.86
  - row_1:
      coordinates:
      - x: 27.15
        y: -10.55
      - x: 27.6
        y: -13.5
      - x: 28.05
        y: -16.45
      - x: 28.45
        y: -19.4
      - x: 28.89
        y: -22.35
      - x: 29.35
        y: -25.35
      - x: 29.8
        y: -28.4
      - x: 30.2
        y: -31.05
      - x: 30.54
        y: -33.7
      orientation: 4.86
  - row_2:
      coordinates:
      - x: 25.79
        y: -10.7
      - x: 26.25
        y: -13.7
      - x: 26.7
        y: -16.65
      - x: 27.14
        y: -19.59
      - x: 27.6
        y: -22.6
      - x: 28.04
        y: -25.55
      - x: 28.5
        y: -28.55
      - x: 28.84
        y: -31.19
      - x: 29.25
        y: -33.9
      orientation: 4.86
  - row_3:
      coordinates:
      - x: 24.5
        y: -10.9
      - x: 24.95
        y: -13.9
      - x: 25.4
        y: -16.84
      - x: 25.8
        y: -19.8
      - x: 26.25
        y: -22.8
      - x: 26.7
        y: -25.7
      - x: 27.15
        y: -28.75
      - x: 27.55
        y: -31.4
      - x: 27.9
        y: -34.05
      orientation: 4.86
  - row_4:
      coordinates:
      - x: 23.2
        y: -11.05
      - x: 23.65
        y: -14.1
      - x: 24.05
        y: -17.05
      - x: 24.49
        y: -20.0
      - x: 24.95
        y: -22.95
      - x: 25.39
        y: -25.9
      - x: 25.85
        y: -28.9
      - x: 26.2
        y: -31.6
      - x: 26.6
        y: -34.25
      orientation: 4.86
  - row_5:
      coordinates:
      - x: 21.88
        y: -11.28
      - x: 22.35
        y: -14.29
      - x: 22.77
        y: -17.24
      - x: 23.19
        y: -20.18
      - x: 23.65
        y: -23.15
      - x: 24.07
        y: -26.13
      - x: 24.49
        y: -29.1
      - x: 24.9
        y: -31.8
      - x: 25.3
        y: -34.45
      orientation: 4.86
  - row_6:
      coordinates:
      - x: 20.47
        y: -11.17
      - x: 20.89
        y: -14.15
      - x: 21.37
        y: -17.15
      - x: 21.82
        y: -20.12
      - x: 22.22
        y: -23.11
      - x: 22.65
        y: -26.08
      - x: 23.1
        y: -29.01
      - x: 23.53
        y: -32.05
      - x: 24.12
        y: -35.26
      orientation: 4.86
